### ISSUE TITLE
Hi bác

### ISSUE THREAD

**Issue by conqdat** [Lang0808/GolangLibs#1]
Hi bác,

Tôi lướt leetcode thì vô tình thấy profile của bác, thật sự rất ấn tượng và đáng ngưỡng mộ.

Nên tôi mới connect với bác. Tôi đang luyệt leetcode cho những mục tiêu nghề nghiệp sắp tới của mình, nên tôi mới ib và hỏi bác lộ trình bác luyện tập, tài liệu cũng như những điều cần tránh khi luyện.

Cám ơn bác nhiều. Mong bác sớm rep. Chúc bác một ngày vui vẻ !

**Comment by Lang0808** [comment]
Hi bạn. Mình thường đọc tài liệu trên VNOI á. Còn lời khuyên thì là luyện tập nhiều thôi, làm nhiều thì bạn sẽ có cảm nhận để giải bài à.
